import { motion } from "framer-motion";
import { useSearchParams } from "react-router-dom";
import { Download, Shield, FileText, Scale, Loader2 } from "lucide-react";
import Navbar from "@/components/Navbar";
import AnimatedBackground from "@/components/AnimatedBackground";
import GlowCursor from "@/components/GlowCursor";
import Footer from "@/components/Footer";
import { useEffect, useState } from "react";
import { API_BASE_URL } from "../config";

const EvidenceReport = () => {
  const [params] = useSearchParams();
  const caseId = params.get("caseId") || "SG-DEMO";
  
  const [status, setStatus] = useState(params.get("status") || "");
  const [confidence, setConfidence] = useState(params.get("confidence") || "");
  const [forensic, setForensic] = useState(params.get("forensic") || "");
  const [risk, setRisk] = useState(params.get("risk") || "");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    // If parameters are already complete, bypass lookups
    if (params.get("status") && params.get("confidence") && params.get("forensic") && params.get("risk")) {
      return;
    }

    const loadCase = async () => {
      setLoading(true);
      
      // 1. Try local storage cache
      const cached = localStorage.getItem("sheguard_cases");
      if (cached) {
        const localCases = JSON.parse(cached);
        const match = localCases.find((c: any) => c.caseId === caseId);
        if (match) {
          setStatus(match.imageStatus);
          setConfidence(String(match.confidenceScore));
          setForensic(String(match.forensicScore));
          setRisk(match.riskLevel);
          setLoading(false);
          return;
        }
      }

      // 2. Try fetching from backend API
      try {
        const response = await fetch(`${API_BASE_URL}/api/cases`);
        if (response.ok) {
          const data = await response.json();
          const match = data.find((c: any) => c.caseId === caseId);
          if (match) {
            setStatus(match.imageStatus);
            setConfidence(String(match.confidenceScore));
            setForensic(String(match.forensicScore));
            setRisk(match.riskLevel);
          }
        }
      } catch (err) {
        console.error("Failed to dynamically fetch case details", err);
      } finally {
        setLoading(false);
      }
    };

    loadCase();
  }, [caseId, params]);

  const displayStatus = status || "Manipulated";
  const displayConfidence = confidence || "92.3";
  const displayForensic = forensic || "87.5";
  const displayRisk = risk || "red";

  const riskTextClass = displayRisk === "green" ? "risk-safe" : displayRisk === "yellow" ? "risk-suspicious" : "risk-manipulated";

  const handleDownload = () => {
    const content = `
SHE-GUARD AI - CYBER FORENSIC EVIDENCE REPORT
===============================================

CASE INFORMATION
  Case ID: ${caseId}
  Date: ${new Date().toLocaleDateString()}
  Time: ${new Date().toLocaleTimeString()}

AI ANALYSIS RESULT
  Image Status: ${displayStatus}
  Confidence Score: ${displayConfidence}%
  Forensic Score: ${displayForensic}%

LEGAL RECOMMENDATION
  Based on the forensic analysis, this image shows signs of digital manipulation.
  It is recommended to file a formal complaint with the Cybercrime Portal (cybercrime.gov.in)
  and preserve this report as digital evidence.

DISCLAIMER
  This report is generated by SHE-GUARD AI forensic analysis system.
  Results should be corroborated with professional forensic examination.

===============================================
Generated by SHE-GUARD AI | ${new Date().toISOString()}
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `SHE-GUARD-Report-${caseId}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="relative min-h-screen cyber-grid">
      <AnimatedBackground />
      <GlowCursor />
      <Navbar />
      <main className="mx-auto max-w-3xl px-4 pb-24 pt-28">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <div className="mb-8 flex items-center justify-center gap-3">
            <Shield className="h-8 w-8 text-neon-purple" />
            <h1 className="font-display text-2xl font-bold tracking-wide sm:text-3xl">
              <span className="gradient-text">Evidence Report</span>
            </h1>
          </div>

          <div className="glass-card neon-border overflow-hidden">
            {loading ? (
              <div className="flex flex-col items-center justify-center py-20 text-muted-foreground gap-3">
                <Loader2 className="h-10 w-10 animate-spin text-neon-purple" />
                <p className="font-mono text-xs uppercase tracking-wider">Locating Forensic Log {caseId}...</p>
              </div>
            ) : (
              <>
                {/* Header */}
                <div className="border-b border-border p-6" style={{ background: "linear-gradient(135deg, hsl(270 80% 65% / 0.1), hsl(200 100% 55% / 0.05))" }}>
                  <div className="flex items-center justify-between">
                    <div>
                      <p className="text-xs uppercase tracking-wider text-muted-foreground">Case ID</p>
                      <p className="font-display text-lg font-bold">{caseId}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs uppercase tracking-wider text-muted-foreground">Date</p>
                      <p className="text-sm">{new Date().toLocaleDateString()}</p>
                    </div>
                  </div>
                </div>

                {/* Sections */}
                <div className="divide-y divide-border">
                  <Section icon={FileText} title="Case Information">
                    <InfoRow label="Case ID" value={caseId} />
                    <InfoRow label="Report Generated" value={new Date().toLocaleString()} />
                    <InfoRow label="System" value="SHE-GUARD AI v1.0" />
                  </Section>

                  <Section icon={Shield} title="AI Analysis Result">
                    <InfoRow label="Image Status" value={displayStatus} valueClass={riskTextClass} />
                    <InfoRow label="Confidence Score" value={`${displayConfidence}%`} />
                    <InfoRow label="Forensic Score" value={`${displayForensic}%`} />
                  </Section>

                  <Section icon={Scale} title="Legal Recommendation">
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      Based on the forensic analysis, this image shows signs of digital manipulation.
                      It is recommended to file a formal complaint with the{" "}
                      <a href="https://cybercrime.gov.in" target="_blank" rel="noopener noreferrer" className="text-neon-blue underline">
                        National Cybercrime Reporting Portal
                      </a>{" "}
                      and preserve this report as digital evidence for legal proceedings.
                    </p>
                  </Section>
                </div>

                {/* Footer */}
                <div className="p-6">
                  <button onClick={handleDownload} className="btn-glow flex w-full items-center justify-center gap-2 font-display text-sm tracking-wide text-primary-foreground">
                    <Download className="h-4 w-4" />
                    Download Evidence Report
                  </button>
                </div>
              </>
            )}
          </div>
        </motion.div>
      </main>
      <Footer />
    </div>
  );
};

const Section = ({ icon: Icon, title, children }: { icon: React.ElementType; title: string; children: React.ReactNode }) => (
  <div className="p-6">
    <div className="mb-3 flex items-center gap-2">
      <Icon className="h-4 w-4 text-neon-purple" />
      <h3 className="font-display text-xs font-semibold uppercase tracking-wider text-muted-foreground">{title}</h3>
    </div>
    <div className="space-y-2">{children}</div>
  </div>
);

const InfoRow = ({ label, value, valueClass }: { label: string; value: string; valueClass?: string }) => (
  <div className="flex justify-between text-sm">
    <span className="text-muted-foreground">{label}</span>
    <span className={valueClass || "text-foreground font-medium"}>{value}</span>
  </div>
);

export default EvidenceReport;
